title: Tingyu Song's Blog
description: 
author: Tingyu Song
avatar: /logo.jpg
email: songty404@gmail.com

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
disqus:
tingyusong.disqus.com/admin

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
logo: logo.jpg
social:
  name: Tingyu Song
  links:
    - https://github.com/SighingSnow
google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: en
